sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t timbilt/frontend -f Dockerfile.dev .
script:
  - docker run -e CI=true timbilt/frontend npm run test
deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'docker-frontend'
  env: 'Dockerfrontend-env'
  bucket_name: 'elasticbeanstalk-us-east-1-268277632823'
  bucket_path: 'docker-frontend'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
